#pragma once

PHP_FUNCTION(Shall_forbidden__construct);
PHP_FUNCTION(Shall_Base_Formatter_getOption);
PHP_FUNCTION(Shall_Base_Formatter_setOption);

PHP_FUNCTION(Shall_Base_Formatter_start_document);
PHP_FUNCTION(Shall_Base_Formatter_start_document);
PHP_FUNCTION(Shall_Base_Formatter_end_document);
PHP_FUNCTION(Shall_Base_Formatter_start_token);
PHP_FUNCTION(Shall_Base_Formatter_end_token);
PHP_FUNCTION(Shall_Base_Formatter_write_token);
PHP_FUNCTION(Shall_Base_Formatter_start_lexing);
PHP_FUNCTION(Shall_Base_Formatter_end_lexing);
